<?php
/**
 * Limesharp_Stockists extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Limesharp
 * @package   Limesharp_Stockists
 * @copyright 2016 Claudiu Creanga
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Claudiu Creanga
 */
 ?>
 
<?php /** @var \Limesharp\Stockists\Block\Stores $block */?>
<?php $_store = $block->getCurrentStore();?>
<?php $data = $block->getStoresForFrontend(); ?>

<div id="map-canvas" style="height: 100%; width: 100%;"></div>

<div class="search-stockists">
	
	<div class="search-header">

		<p class="search-title"><?php echo __("Find a stockist") ?></p>
		<p class="stockists-intro"><?php echo __("Enter a city, country or full post/zip code") ?></p>
		<input id="stockist-search-term" type="text" placeholder="Search" /> 
		<button id="stockists-submit"><?php echo __("Search") ?></button>
		
	</div>
	<div class="stockists-results">
		

		<div class="results-store">
			
			<?php foreach ($data as $item): ?>
			

		        <?php $data_marker = $item["latitude"].$item["longitude"]; ?>				        
		        
	        	<div class="results-content loaded-results" data-marker="<?php echo $data_marker; ?>">
		        	
		        	<?php if($item["image"]): ?>
		        		
		        		<div class="image">
				        		<img src="<?php echo $block->getBaseImageUrl()."limesharp_stockists/stockist/image/".$item["image"] ?>" alt="<?php echo $item["name"] ?>" /> 
		        		</div>
		        		
		        	<?php endif; ?>
		        	
		        	
		        	<p class="results-title"><?php echo $item["name"] ?></p>
		        	<p class="results-address"><?php echo $item["address"] ?></p>
		        	<p class="results-phone"><?php echo $item["city"]." ".$item["postcode"] ?></p>
		        	<p class="results-miles"><?php echo $item["country"] ?></p>
		        	
	        	</div>	
		        	
	        
	        <?php endforeach; ?>
	        			
		</div>
		
	</div>
</div>



<script type="text/x-magento-init">
	{
		"*": {
		        
        	"stockists_widget": " <?php echo "test" ?> "
	        	
	    }
    }
</script>
<script>
	
    window.map_pin = '<?php echo $block->getViewFileUrl('Limesharp_Stockists::images/map_pin.png') ?>';
    
    require([
        'limesharp_stockists'
    ], function ($) {
	    
    });
</script>